### PR TITLE
fix 5.12 sys-kernel/surface-sources-5.12 emerge

### PR DESCRIPTION
**Pull request by LeoAlex0**
A solution for issue #5 , tested on `Surface Pro 4`, may need improvement.

### CODE REVIEW

**Comment by parinzee** [comment]
Right I can see how that would fix the problem. Thank you for your contribution, however, by removing the gentoo patches **(if I am correct)** we would be removing some of the essential options in the kernel, namely the "Gentoo Linux" menu.

Maybe it would be better if we were to decrement the K_GENPATCHES variable to a lower or higher version based on https://dev.gentoo.org/~mpagano/genpatches/releases-5.12.html.

Also, I believe this commit has something to do with it, you can take a look: https://github.com/Parinz/linux-surface-overlay/commit/100777a6c1c2ea1c40b230821a8a733309972454

Thank you very much for contributing and I hope you achieve a success.

PS: You can also generate manifests for your ebuild by doing `pkgdev manifest -m`, if it's not installed just emerge it.

**Comment by LeoAlex0** [comment]
> Right I can see how that would fix the problem. Thank you for your contribution, however, by removing the gentoo patches **(if I am correct)** we would be removing some of the essential options in the kernel, namely the "Gentoo Linux" menu.
> 
> Maybe it would be better if we were to decrement the K_GENPATCHES variable to a lower or higher version based on https://dev.gentoo.org/~mpagano/genpatches/releases-5.12.html.
> 
> Also, I believe this commit has something to do with it, you can take a look: [100777a](https://github.com/Parinz/linux-surface-overlay/commit/100777a6c1c2ea1c40b230821a8a733309972454)
> 
> Thank you very much for contributing and I hope you achieve a success.
> 
> PS: You can also generate manifests for your ebuild by doing `pkgdev manifest -m`, if it's not installed just emerge it.

I see, I think I found the right version of gen-patches.
For now, I added gentoo patches.

Thanks for your reminding.

**Comment by parinzee** [comment]
Looks clean. You ready to merge?

**Comment by LeoAlex0** [comment]
> Looks clean. You ready to merge?

Yes

**Pull request merged**
